services:
  - type: web
    name: eemc-object-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python flask_backend_cloud_box_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
